import uuid from "react-uuid";
import Agamemnon from "./images/Agamemnon.jpg";
import ComtesseDeBrionne from "./images/ComtesseDeBrionne.jpg";
import Hector from "./images/Hector.jpg";
import Alcyon from "./images/Alcyon.jpg";
import BonneSophie from "./images/BonneSophie.jpg";
import Atlas from "./images/Atlas.jpg";

export const slaveTradeData = [
    {
        ID: uuid(),
        "Vessel-Name": "Hector",
        "Vessel-Image": Hector,
        "Principal-Purchase-Location": "West Central Africa and St. Helena",
        "Captain's name": "Fraser, James",
        "Purchase-Location": "San Juan, Puerto Rico",
        "Purchase-Latitude": 18.452689,
        "Purchase-Longitude": -66.097588,
        "Disembarkment-Location": "Charleston, South Carolina",
        "Disembarkment-Latitude": 32.745318,
        "Disembarkment-Longitude": -79.847956,
        "Slave-Count": 550,
        "Trade-Year": 1780,
        active: true,
    },
    {
        ID: uuid(),
        "Vessel-Name": "Comtesse de Brionne",
        "Vessel-Image": ComtesseDeBrionne,
        "Principal-Purchase-Location": "Iles de Los",
        "Captain's name": "Chilcott, John",
        "Purchase-Location": "Kingstown, Saint Vincent and the Grenadines",
        "Purchase-Latitude": 13.157301,
        "Purchase-Longitude": -61.247022,
        "Disembarkment-Location": "Port Royal, Jamaica",
        "Disembarkment-Latitude": 17.932233,
        "Disembarkment-Longitude": -76.840039,
        "Slave-Count": 750,
        "Trade-Year": 1740,
        active: false,
    },
    {
        ID: uuid(),
        "Vessel-Name": "Alcyon",
        "Vessel-Image": Alcyon,
        "Principal-Purchase-Location": "Loango, Congo",
        "Captain's name": "Papin, Jacques",
        "Purchase-Location": "Fortaleza, Brazil",
        "Purchase-Latitude": -3.722202,
        "Purchase-Longitude": -38.518233,
        "Disembarkment-Location": "New York",
        "Disembarkment-Latitude": 40.546505,
        "Disembarkment-Longitude": -73.912768,
        "Slave-Count": 700,
        "Trade-Year": 1776,
        active: false,
    },
    {
        ID: uuid(),
        "Vessel-Name": "Bonne Sophie",
        "Vessel-Image": BonneSophie,
        "Principal-Purchase-Location": "Porto-Novo, Benin",
        "Captain's name": "Fallouard, Victor",
        "Purchase-Location": "Porto-Novo, Benin",
        "Purchase-Latitude": 6.475429,
        "Purchase-Longitude": 2.61854,
        "Disembarkment-Location": "Rio das Ostras, Brazil",
        "Disembarkment-Latitude": -22.540676,
        "Disembarkment-Longitude": -41.928766,
        "Slave-Count": 424,
        "Trade-Year": 1810,
        active: false,
    },
    {
        ID: uuid(),
        "Vessel-Name": "Atlas",
        "Vessel-Image": Atlas,
        "Principal-Purchase-Location": "Cabinda",
        "Captain's name": "Ozelle, Ch-Laurent",
        "Purchase-Location": "Hispanolia",
        "Purchase-Latitude": 19.842935,
        "Purchase-Longitude": -73.382336,
        "Disembarkment-Location": "Nassau, Bahamas",
        "Disembarkment-Latitude": 25.005376,
        "Disembarkment-Longitude": -77.33135,
        "Slave-Count": 469,
        "Trade-Year": 1763,
        active: false,
    },
    {
        ID: uuid(),
        "Vessel-Name": "Agamemnon",
        "Vessel-Image": Agamemnon,
        "Principal-Purchase-Location": "Luanda, Angola",
        "Captain's name": "Lemasson, Auguste-Stanislas",
        "Purchase-Location": "Georgetown, Guyana",
        "Purchase-Latitude": 6.823489,
        "Purchase-Longitude": -58.162853,
        "Disembarkment-Location": "Bridgetown, Barbados",
        "Disembarkment-Latitude": 13.095913,
        "Disembarkment-Longitude": -59.619945,
        "Slave-Count": 674,
        "Trade-Year": 1801,
        active: false,
    },
];
