[
    {
        ID: uuid(),
        "Voyage-ID": 10803,
        "Vessel-Name": "Louisa Margarita",
        "Voyage-Origin": "Amsterdam",
        "Purchase-Latitude": 52.38028,
        "Purchase-Longitude": 4.902191,
        "Principal-Purchase-Location": "Windward + Ivory + Gold + Benin",
        "Voyage-Disembarkation": "Suriname",
        "Disembarkment-Latitude": 6.047404456,
        "Disembarkment-Longitude": -54.5506,
        "Trade-Year": 1747,
        "Slave-Count": 543,
        "Captain's name": "Lindenberg, J",
        active: true,
    },
    {
        ID: uuid(),
        "Voyage-ID": 19250,
        "Vessel-Name": "Rainha dos Anjos",
        "Voyage-Origin": "Bahia, port unspecified",
        "Purchase-Latitude": -13.23797599,
        "Purchase-Longitude": -38.91553297,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Rio de Janeiro",
        "Disembarkment-Latitude": -22.98062149,
        "Disembarkment-Longitude": -43.15429688,
        "Trade-Year": 1807,
        "Slave-Count": 505,
        "Captain's name": "Santana, JosÃ© AntÃ´nio de",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31690,
        "Vessel-Name": "Aigle",
        "Voyage-Origin": "Bordeaux",
        "Purchase-Latitude": 44.84808026,
        "Purchase-Longitude": -1.285400391,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.2008068,
        "Trade-Year": 1787,
        "Slave-Count": 526,
        "Captain's name": "Babinot",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31637,
        "Vessel-Name": "Nairac",
        "Voyage-Origin": "Bordeaux",
        "Purchase-Latitude": 44.36313311,
        "Purchase-Longitude": -1.384277344,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Jamaica, port unspecified",
        "Disembarkment-Latitude": 18.25487608,
        "Disembarkment-Longitude": -77.22290039,
        "Trade-Year": 1779,
        "Slave-Count": 697,
        "Captain's name": "Babinot, Antoine",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31633,
        "Vessel-Name": "Pactole",
        "Voyage-Origin": "Bordeaux",
        "Purchase-Latitude": 45.59446298,
        "Purchase-Longitude": -1.180392562,
        "Principal-Purchase-Location": "Ardra",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1778,
        "Slave-Count": 609,
        "Captain's name": "Chevillard, Fleury",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31711,
        "Vessel-Name": "Arada",
        "Voyage-Origin": "Bordeaux",
        "Purchase-Latitude": 44.84029065,
        "Purchase-Longitude": -0.582275391,
        "Principal-Purchase-Location": "Porto Novo",
        "Voyage-Disembarkation": "Saint-Domingue, port unspecified",
        "Disembarkment-Latitude": 18.43420029,
        "Disembarkment-Longitude": -69.92797852,
        "Trade-Year": 1788,
        "Slave-Count": 574,
        "Captain's name": "Desmartis, Jean",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 17545,
        "Vessel-Name": "Cornwall",
        "Voyage-Origin": "Bristol",
        "Purchase-Latitude": 51.4538022,
        "Purchase-Longitude": -2.5972985,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Saint John (Antigua)",
        "Disembarkment-Latitude": 17.1184569,
        "Disembarkment-Longitude": -61.8448509,
        "Trade-Year": 1763,
        "Slave-Count": 535,
        "Captain's name": "Duncomb, David",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 17921,
        "Vessel-Name": "Hector",
        "Voyage-Origin": "Bristol",
        "Purchase-Latitude": 51.54377587,
        "Purchase-Longitude": -2.978593959,
        "Principal-Purchase-Location": "Cape Coast Castle",
        "Voyage-Disembarkation": "Savanna la Mar",
        "Disembarkment-Latitude": 18.20541039,
        "Disembarkment-Longitude": -78.13779883,
        "Trade-Year": 1785,
        "Slave-Count": 514,
        "Captain's name": "Llewellin, William Ball, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 18144,
        "Vessel-Name": "Hector",
        "Voyage-Origin": "Bristol",
        "Purchase-Latitude": 51.45639384,
        "Purchase-Longitude": -2.841678489,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "St. Vincent, port unspecified",
        "Disembarkment-Latitude": 13.153317,
        "Disembarkment-Longitude": -61.231507,
        "Trade-Year": 1793,
        "Slave-Count": 558,
        "Captain's name": "Fraser, James",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 17506,
        "Vessel-Name": "Hector",
        "Voyage-Origin": "Bristol",
        "Purchase-Latitude": 51.37979697,
        "Purchase-Longitude": -3.059086716,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Upper James River",
        "Disembarkment-Latitude": 36.83579725,
        "Disembarkment-Longitude": -75.89756159,
        "Trade-Year": 1762,
        "Slave-Count": 512,
        "Captain's name": "Chilcott, John",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31862,
        "Vessel-Name": "Comtesse de Brionne",
        "Voyage-Origin": "Dunkerque",
        "Purchase-Latitude": 51.0572884,
        "Purchase-Longitude": 2.33266735,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1766,
        "Slave-Count": 646,
        "Captain's name": "Romain, J-F",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31970,
        "Vessel-Name": "Bonne Sophie",
        "Voyage-Origin": "Honfleur",
        "Purchase-Latitude": 49.42704056,
        "Purchase-Longitude": 0.23059118,
        "Principal-Purchase-Location": "Iles de Los",
        "Voyage-Disembarkation": "Cayes (Les)",
        "Disembarkment-Latitude": 18.18515462,
        "Disembarkment-Longitude": -73.74283964,
        "Trade-Year": 1788,
        "Slave-Count": 556,
        "Captain's name": "Fallouard, Victor",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32342,
        "Vessel-Name": "Aimable Louise",
        "Voyage-Origin": "La Rochelle",
        "Purchase-Latitude": 46.1591126,
        "Purchase-Longitude": -1.1520434,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1784,
        "Slave-Count": 527,
        "Captain's name": "Bertrand, J",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32329,
        "Vessel-Name": "Pyrrha",
        "Voyage-Origin": "La Rochelle",
        "Purchase-Latitude": 46.15631757,
        "Purchase-Longitude": -1.153509899,
        "Principal-Purchase-Location": "Gold Coast, Fr. definition",
        "Voyage-Disembarkation": "Jamaica, port unspecified",
        "Disembarkment-Latitude": 18.25487608,
        "Disembarkment-Longitude": -78.37876743,
        "Trade-Year": 1779,
        "Slave-Count": 570,
        "Captain's name": "Dubois, Guillaume",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32439,
        "Vessel-Name": "Bonhomme Richard",
        "Voyage-Origin": "La Rochelle",
        "Purchase-Latitude": 46.15468404,
        "Purchase-Longitude": -1.155500436,
        "Principal-Purchase-Location": "Porto Novo",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1791,
        "Slave-Count": 538,
        "Captain's name": "Papin, Jacques",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32227,
        "Vessel-Name": "Alcyon",
        "Voyage-Origin": "La Rochelle",
        "Purchase-Latitude": 46.15700726,
        "Purchase-Longitude": -1.158066602,
        "Principal-Purchase-Location": "Loango",
        "Voyage-Disembarkation": "Saint John (Antigua)",
        "Disembarkment-Latitude": 17.1184569,
        "Disembarkment-Longitude": -61.8448509,
        "Trade-Year": 1755,
        "Slave-Count": 511,
        "Captain's name": "ManiÃ©, Jean",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32704,
        "Vessel-Name": "Atlas",
        "Voyage-Origin": "Le Havre",
        "Purchase-Latitude": 49.49297846,
        "Purchase-Longitude": 0.091885931,
        "Principal-Purchase-Location": "Cabinda",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1786,
        "Slave-Count": 624,
        "Captain's name": "Ozelle, Ch-Laurent",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32815,
        "Vessel-Name": "AssemblÃe Nationale",
        "Voyage-Origin": "Le Havre",
        "Purchase-Latitude": 49.4909361,
        "Purchase-Longitude": 0.09634111,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Havana",
        "Disembarkment-Latitude": 23.14390417,
        "Disembarkment-Longitude": -82.36447098,
        "Trade-Year": 1791,
        "Slave-Count": 501,
        "Captain's name": "CorbillÃ, J-Fr",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32693,
        "Vessel-Name": "Agamemnon",
        "Voyage-Origin": "Le Havre",
        "Purchase-Latitude": 49.49522496,
        "Purchase-Longitude": 0.098752525,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Leogane",
        "Disembarkment-Latitude": 18.52460838,
        "Disembarkment-Longitude": -72.66575224,
        "Trade-Year": 1785,
        "Slave-Count": 526,
        "Captain's name": "Lemasson, Auguste-Stanislas",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32749,
        "Vessel-Name": "Atlas",
        "Voyage-Origin": "Le Havre",
        "Purchase-Latitude": 49.48736176,
        "Purchase-Longitude": 0.097338432,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1788,
        "Slave-Count": 552,
        "Captain's name": "Damar, Augustin",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 48502,
        "Vessel-Name": "Anjo do Senhor",
        "Voyage-Origin": "Lisbon",
        "Purchase-Latitude": 38.70595137,
        "Purchase-Longitude": -9.13784878,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Bahia, port unspecified",
        "Disembarkment-Latitude": -13.03246755,
        "Disembarkment-Longitude": -38.52509108,
        "Trade-Year": 1798,
        "Slave-Count": 689,
        "Captain's name": "Santos, Manoel Joaquim dos",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 48406,
        "Vessel-Name": "NS de Oliveira",
        "Voyage-Origin": "Lisbon",
        "Purchase-Latitude": 38.70685104,
        "Purchase-Longitude": -9.131821476,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1786,
        "Slave-Count": 610,
        "Captain's name": "Rodrigues, JosÃ-Feliz",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 48383,
        "Vessel-Name": "NS da ConceiÃ§Ão e S Rita",
        "Voyage-Origin": "Lisbon",
        "Purchase-Latitude": 38.70501079,
        "Purchase-Longitude": -9.145078918,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Maranhao",
        "Disembarkment-Latitude": -2.008823348,
        "Disembarkment-Longitude": -44.41044036,
        "Trade-Year": 1785,
        "Slave-Count": 606,
        "Captain's name": "Madeira, Joaquim LÃ¡zaro",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 19507,
        "Vessel-Name": "S JosÃ",
        "Voyage-Origin": "Lisbon",
        "Purchase-Latitude": 38.68159207,
        "Purchase-Longitude": 9.350660553,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Pernambuco, port unspecified",
        "Disembarkment-Latitude": -8.764301188,
        "Disembarkment-Longitude": -35.04996664,
        "Trade-Year": 1775,
        "Slave-Count": 550,
        "Captain's name": "Almeida, Manoel Gomes de",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 19126,
        "Vessel-Name": "Bela Elisa",
        "Voyage-Origin": "Lisbon",
        "Purchase-Latitude": 38.7030887,
        "Purchase-Longitude": -9.161636184,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Rio de Janeiro",
        "Disembarkment-Latitude": -22.98062149,
        "Disembarkment-Longitude": -43.0989239,
        "Trade-Year": 1801,
        "Slave-Count": 829,
        "Captain's name": "Vieira, Manoel JosÃ©",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 90685,
        "Vessel-Name": "Glory",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.4098856,
        "Purchase-Longitude": -3.002160017,
        "Principal-Purchase-Location": "Bight of Benin, port unspecified",
        "Voyage-Disembarkation": "Barbados, port unspecified",
        "Disembarkment-Latitude": 13.08984802,
        "Disembarkment-Longitude": -59.62427585,
        "Trade-Year": 1760,
        "Slave-Count": 516,
        "Captain's name": "Chalmers, Thomas Speers, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 90830,
        "Vessel-Name": "Rumbold",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.40507477,
        "Purchase-Longitude": -3.014002546,
        "Principal-Purchase-Location": "Loango",
        "Voyage-Disembarkation": "Basse-Terre",
        "Disembarkment-Latitude": 15.99508691,
        "Disembarkment-Longitude": -61.7337405,
        "Trade-Year": 1760,
        "Slave-Count": 682,
        "Captain's name": "Maddock, James & Sacheverell, John",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 83989,
        "Vessel-Name": "Washington",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.40432498,
        "Purchase-Longitude": -2.998070849,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Charleston",
        "Disembarkment-Latitude": 32.77017864,
        "Disembarkment-Longitude": -79.92131751,
        "Trade-Year": 1805,
        "Slave-Count": 530,
        "Captain's name": "Belcher & Waldo",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 82141,
        "Vessel-Name": "King George",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.40010716,
        "Purchase-Longitude": -3.01185233,
        "Principal-Purchase-Location": "Congo River",
        "Voyage-Disembarkation": "Demerara",
        "Disembarkment-Latitude": 6.837124989,
        "Disembarkment-Longitude": -58.07356319,
        "Trade-Year": 1798,
        "Slave-Count": 540,
        "Captain's name": "Hensley, Samuel",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 83364,
        "Vessel-Name": "Rodney",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.40794884,
        "Purchase-Longitude": -2.986278264,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Dominica, port unspecified",
        "Disembarkment-Latitude": 15.33496,
        "Disembarkment-Longitude": -61.407186,
        "Trade-Year": 1784,
        "Slave-Count": 530,
        "Captain's name": "Caton, Joseph & Oates, Richard",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81609,
        "Vessel-Name": "Golden Age",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.41769424,
        "Purchase-Longitude": -3.018714821,
        "Principal-Purchase-Location": "Popo",
        "Voyage-Disembarkation": "Grenada, port unspecified",
        "Disembarkment-Latitude": 12.05380509,
        "Disembarkment-Longitude": -61.75897064,
        "Trade-Year": 1791,
        "Slave-Count": 536,
        "Captain's name": "Fayrer, Joseph",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81823,
        "Vessel-Name": "Hero",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.4259386,
        "Purchase-Longitude": -3.008757202,
        "Principal-Purchase-Location": "Cape Coast Castle",
        "Voyage-Disembarkation": "Havana",
        "Disembarkment-Latitude": 23.14390417,
        "Disembarkment-Longitude": -82.36447098,
        "Trade-Year": 1791,
        "Slave-Count": 519,
        "Captain's name": "Davis, John<br/> Horsley, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 90689,
        "Vessel-Name": "Prince Tom",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.3969008,
        "Purchase-Longitude": -2.936109904,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Jamaica, port unspecified",
        "Disembarkment-Latitude": 18.25487608,
        "Disembarkment-Longitude": -78.37876743,
        "Trade-Year": 1758,
        "Slave-Count": 683,
        "Captain's name": "Cooke, Charles & Smith, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81248,
        "Vessel-Name": "Elliott",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.37646179,
        "Purchase-Longitude": -2.92646309,
        "Principal-Purchase-Location": "Lagos, Onim",
        "Voyage-Disembarkation": "Kingston",
        "Disembarkment-Latitude": 17.94236728,
        "Disembarkment-Longitude": -76.83042146,
        "Trade-Year": 1786,
        "Slave-Count": 898,
        "Captain's name": "Cleminson, John",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81550,
        "Vessel-Name": "Garland",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.42913614,
        "Purchase-Longitude": -2.968756724,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "La Guaira",
        "Disembarkment-Latitude": 10.5390525,
        "Disembarkment-Longitude": 10.5390525,
        "Trade-Year": 1787,
        "Slave-Count": 604,
        "Captain's name": "Forbes, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 82167,
        "Vessel-Name": "Kingsmill",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.49831164,
        "Purchase-Longitude": -3.08279472,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Martinique, port unspecified",
        "Disembarkment-Latitude": 14.58390168,
        "Disembarkment-Longitude": -61.0774718,
        "Trade-Year": 1798,
        "Slave-Count": 627,
        "Captain's name": "Mullion, Thomas",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81987,
        "Vessel-Name": "Jane",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.42945516,
        "Purchase-Longitude": -3.136868626,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Montego Bay",
        "Disembarkment-Latitude": 18.4724603,
        "Disembarkment-Longitude": -77.9217357,
        "Trade-Year": 1781,
        "Slave-Count": 620,
        "Captain's name": "Hewan, John",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 82096,
        "Vessel-Name": "Juba",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.39881642,
        "Purchase-Longitude": -3.196297231,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Saint John (Antigua)",
        "Disembarkment-Latitude": 17.1184569,
        "Disembarkment-Longitude": -61.8448509,
        "Trade-Year": 1784,
        "Slave-Count": 504,
        "Captain's name": "Kilvington, John & Higginson",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81552,
        "Vessel-Name": "Garland",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.55049046,
        "Purchase-Longitude": -2.916246677,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "St. Kitts, port unspecified",
        "Disembarkment-Latitude": 17.26016805,
        "Disembarkment-Longitude": -62.66366169,
        "Trade-Year": 1789,
        "Slave-Count": 605,
        "Captain's name": "Forbes, William",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 83622,
        "Vessel-Name": "Stag",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.57226042,
        "Purchase-Longitude": -3.035330316,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "St. Lucia, port unspecified",
        "Disembarkment-Latitude": 13.80849429,
        "Disembarkment-Longitude": -60.89410364,
        "Trade-Year": 1782,
        "Slave-Count": 623,
        "Captain's name": "Butler, Henry",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 81559,
        "Vessel-Name": "Gascoyne",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.32533374,
        "Purchase-Longitude": -2.783311109,
        "Principal-Purchase-Location": "Calabar",
        "Voyage-Disembarkation": "St. Vincent, port unspecified",
        "Disembarkment-Latitude": 13.153317,
        "Disembarkment-Longitude": -61.231507,
        "Trade-Year": 1786,
        "Slave-Count": 516,
        "Captain's name": "Comberbach, Peter",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 82803,
        "Vessel-Name": "Mosley Hill",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.24590417,
        "Purchase-Longitude": -2.703098775,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Tortola, port unspecified",
        "Disembarkment-Latitude": 18.4210568,
        "Disembarkment-Longitude": -64.6388325,
        "Trade-Year": 1782,
        "Slave-Count": 730,
        "Captain's name": "Hewan, John",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 82807,
        "Vessel-Name": "Mosley Hill",
        "Voyage-Origin": "Liverpool",
        "Purchase-Latitude": 53.4742073,
        "Purchase-Longitude": -3.339893653,
        "Principal-Purchase-Location": "Bonny",
        "Voyage-Disembarkation": "Trinidad, port unspecified",
        "Disembarkment-Latitude": 10.63924775,
        "Disembarkment-Longitude": -60.84652715,
        "Trade-Year": 1786,
        "Slave-Count": 650,
        "Captain's name": "Fayrer, Joseph",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 78824,
        "Vessel-Name": "Adventure",
        "Voyage-Origin": "London",
        "Purchase-Latitude": 51.48999696,
        "Purchase-Longitude": -0.125669229,
        "Principal-Purchase-Location": "Cape Coast Castle",
        "Voyage-Disembarkation": "Barbados, port unspecified",
        "Disembarkment-Latitude": 13.08984802,
        "Disembarkment-Longitude": -59.62427585,
        "Trade-Year": 1748,
        "Slave-Count": 510,
        "Captain's name": "Pickett, John  Piggott",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 83337,
        "Vessel-Name": "Rio Nova",
        "Voyage-Origin": "London",
        "Purchase-Latitude": 51.50557183,
        "Purchase-Longitude": -0.120817527,
        "Principal-Purchase-Location": "Popo",
        "Voyage-Disembarkation": "Black River",
        "Disembarkment-Latitude": 18.02106892,
        "Disembarkment-Longitude": -77.8481116,
        "Trade-Year": 1793,
        "Slave-Count": 569,
        "Captain's name": "Moulton, Richard",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 80917,
        "Vessel-Name": "Comte du Norde",
        "Voyage-Origin": "London",
        "Purchase-Latitude": 51.50657648,
        "Purchase-Longitude": -0.07743308,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Charleston",
        "Disembarkment-Latitude": 32.77017864,
        "Disembarkment-Longitude": -79.92131751,
        "Trade-Year": 1784,
        "Slave-Count": 611,
        "Captain's name": "Penny, James",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 80729,
        "Vessel-Name": "Camden",
        "Voyage-Origin": "London",
        "Purchase-Latitude": 51.50783226,
        "Purchase-Longitude": -0.036271151,
        "Principal-Purchase-Location": "Anomabu",
        "Voyage-Disembarkation": "Jamaica, port unspecified",
        "Disembarkment-Latitude": 18.25487608,
        "Disembarkment-Longitude": -78.37876743,
        "Trade-Year": 1783,
        "Slave-Count": 590,
        "Captain's name": "Wilson, Thomas",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 80093,
        "Vessel-Name": "Africa",
        "Voyage-Origin": "London",
        "Purchase-Latitude": 51.49665461,
        "Purchase-Longitude": 0.030514138,
        "Principal-Purchase-Location": "Anomabu",
        "Voyage-Disembarkation": "Kingston",
        "Disembarkment-Latitude": 17.94236728,
        "Disembarkment-Longitude": -76.83042146,
        "Trade-Year": 1784,
        "Slave-Count": 603,
        "Captain's name": "Charles, James",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32962,
        "Vessel-Name": "Apollon",
        "Voyage-Origin": "Lorient",
        "Purchase-Latitude": 47.74435739,
        "Purchase-Longitude": -3.358175647,
        "Principal-Purchase-Location": "Saint-Louis",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1742,
        "Slave-Count": 645,
        "Captain's name": "Dutertre, J. Michel",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32971,
        "Vessel-Name": "Henriette",
        "Voyage-Origin": "Lorient",
        "Purchase-Latitude": 47.74399529,
        "Purchase-Longitude": -3.347592746,
        "Principal-Purchase-Location": "Goree",
        "Voyage-Disembarkation": "Martinique, port unspecified",
        "Disembarkment-Latitude": 14.58390168,
        "Disembarkment-Longitude": -61.0774718,
        "Trade-Year": 1744,
        "Slave-Count": 536,
        "Captain's name": "Viau, Pierre",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 32987,
        "Vessel-Name": "MarÃ©chal de Lassey",
        "Voyage-Origin": "Lorient",
        "Purchase-Latitude": 47.7405473,
        "Purchase-Longitude": -3.351478887,
        "Principal-Purchase-Location": "Iles de Los",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1783,
        "Slave-Count": 588,
        "Captain's name": "GuÃrard",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33073,
        "Vessel-Name": "Ville de Lausanne",
        "Voyage-Origin": "Marseille",
        "Purchase-Latitude": 43.29497295,
        "Purchase-Longitude": 5.37279751,
        "Principal-Purchase-Location": "Mozambique",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1790,
        "Slave-Count": 550,
        "Captain's name": "Antoine",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33077,
        "Vessel-Name": "Bon MÃ©nage",
        "Voyage-Origin": "Marseille",
        "Purchase-Latitude": 43.29522004,
        "Purchase-Longitude": 5.354969114,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Dominica, port unspecified",
        "Disembarkment-Latitude": 15.33496,
        "Disembarkment-Longitude": -61.407186,
        "Trade-Year": 1793,
        "Slave-Count": 674,
        "Captain's name": "Bazin, Jean-Alain-Alex",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30620,
        "Vessel-Name": "Prince de Conty",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.22123809,
        "Purchase-Longitude": -1.553380349,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1753,
        "Slave-Count": 723,
        "Captain's name": "Masson, FranÃ§ois",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30937,
        "Vessel-Name": "Fortune",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.22709295,
        "Purchase-Longitude": -1.554542626,
        "Principal-Purchase-Location": "Loango",
        "Voyage-Disembarkation": "Cayes (Les)",
        "Disembarkment-Latitude": 18.18515462,
        "Disembarkment-Longitude": -73.74283964,
        "Trade-Year": 1771,
        "Slave-Count": 535,
        "Captain's name": "Charbonneau",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30726,
        "Vessel-Name": "Mars",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.23251209,
        "Purchase-Longitude": -1.547959382,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Jamaica, port unspecified",
        "Disembarkment-Latitude": 18.25487608,
        "Disembarkment-Longitude": -78.37876743,
        "Trade-Year": 1756,
        "Slave-Count": 700,
        "Captain's name": "Deurbroucq, Jean",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30610,
        "Vessel-Name": "Seine",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.23994766,
        "Purchase-Longitude": -1.548016722,
        "Principal-Purchase-Location": "Whydah",
        "Voyage-Disembarkation": "Leogane",
        "Disembarkment-Latitude": 18.52460838,
        "Disembarkment-Longitude": -72.66575224,
        "Trade-Year": 1752,
        "Slave-Count": 585,
        "Captain's name": "Laragon, Thomas",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30505,
        "Vessel-Name": "Suzanne",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.24757991,
        "Purchase-Longitude": -1.543530504,
        "Principal-Purchase-Location": "Cabinda",
        "Voyage-Disembarkation": "Martinique, port unspecified",
        "Disembarkment-Latitude": 14.58390168,
        "Disembarkment-Longitude": -61.0774718,
        "Trade-Year": 1745,
        "Slave-Count": 585,
        "Captain's name": "MahÃ, Joseph",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31239,
        "Vessel-Name": "PÃ¨re de Famille",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.25240387,
        "Purchase-Longitude": -1.538869535,
        "Principal-Purchase-Location": "Cabinda",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1788,
        "Slave-Count": 594,
        "Captain's name": "Vince, Pierre",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 30732,
        "Vessel-Name": "Prince de Conty",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.25857157,
        "Purchase-Longitude": -1.538286113,
        "Principal-Purchase-Location":
            "West Central Africa and St. Helena, port unspecified",
        "Voyage-Disembarkation": "Saint-Domingue, port unspecified",
        "Disembarkment-Latitude": 18.43420029,
        "Disembarkment-Longitude": -69.92960935,
        "Trade-Year": 1756,
        "Slave-Count": 800,
        "Captain's name": "Masson, Fr-Guillaume",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31148,
        "Vessel-Name": "Confiance",
        "Voyage-Origin": "Nantes",
        "Purchase-Latitude": 47.28333026,
        "Purchase-Longitude": -1.52659327,
        "Principal-Purchase-Location": "Porto Novo",
        "Voyage-Disembarkation": "Saint-Marc",
        "Disembarkment-Latitude": 18.61993396,
        "Disembarkment-Longitude": -72.35812661,
        "Trade-Year": 1785,
        "Slave-Count": 528,
        "Captain's name": "Le Ray, Math",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 47522,
        "Vessel-Name": "NS da Boa Viagem Abismo",
        "Voyage-Origin": "Pernambuco, port unspecified",
        "Purchase-Latitude": -9.219151776,
        "Purchase-Longitude": -35.32243836,
        "Principal-Purchase-Location": "Benguela",
        "Voyage-Disembarkation": "Bahia, port unspecified",
        "Disembarkment-Latitude": -13.03246755,
        "Disembarkment-Longitude": -38.52509108,
        "Trade-Year": 1807,
        "Slave-Count": 560,
        "Captain's name": "Silva, SimplÃ­cio da",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 48770,
        "Vessel-Name": "S AntÃ´nio SertÃ³rio",
        "Voyage-Origin": "Pernambuco, port unspecified",
        "Purchase-Latitude": -9.439229685,
        "Purchase-Longitude": -35.52126081,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Bahia, port unspecified",
        "Disembarkment-Latitude": -13.03246755,
        "Disembarkment-Longitude": -38.52509108,
        "Trade-Year": 1797,
        "Slave-Count": 580,
        "Captain's name": "Bastos, JoÃo da Rocha & Flamante, Francisco",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 47529,
        "Vessel-Name": "Amizade",
        "Voyage-Origin": "Rio de Janeiro",
        "Purchase-Latitude": -22.97144343,
        "Purchase-Longitude": -42.85108534,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Bahia, port unspecified",
        "Disembarkment-Latitude": -13.03246755,
        "Disembarkment-Longitude": -38.52509108,
        "Trade-Year": 1810,
        "Slave-Count": 545,
        "Captain's name": "Souza, Alexandre JosÃ da Silveira e",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 8411,
        "Vessel-Name": "Rainha dos Anjos",
        "Voyage-Origin": "Rio de Janeiro",
        "Purchase-Latitude": -23.00477529,
        "Purchase-Longitude": -43.26686608,
        "Principal-Purchase-Location": "Luanda",
        "Voyage-Disembarkation": "Montevideo",
        "Disembarkment-Latitude": -34.91912161,
        "Disembarkment-Longitude": -56.19399,
        "Trade-Year": 1799,
        "Slave-Count": 524,
        "Captain's name": "Santana, JosÃ AntÃ´nio de",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33286,
        "Vessel-Name": "Prince de Conty",
        "Voyage-Origin": "Saint-Malo",
        "Purchase-Latitude": 48.67103805,
        "Purchase-Longitude": -1.989395641,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Cap Francais",
        "Disembarkment-Latitude": 19.76092065,
        "Disembarkment-Longitude": -72.19104178,
        "Trade-Year": 1777,
        "Slave-Count": 862,
        "Captain's name": "CorbillÃ, J-Fr",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33236,
        "Vessel-Name": "Mesny",
        "Voyage-Origin": "Saint-Malo",
        "Purchase-Latitude": 48.64257311,
        "Purchase-Longitude": -2.105663852,
        "Principal-Purchase-Location": "Cabinda",
        "Voyage-Disembarkation": "Leogane",
        "Disembarkment-Latitude": 18.52460838,
        "Disembarkment-Longitude": -72.66575224,
        "Trade-Year": 1768,
        "Slave-Count": 506,
        "Captain's name": "Jallobert de Monville",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33165,
        "Vessel-Name": "Chasseur",
        "Voyage-Origin": "Saint-Malo",
        "Purchase-Latitude": 48.63036894,
        "Purchase-Longitude": -2.154889987,
        "Principal-Purchase-Location": "Whydah",
        "Voyage-Disembarkation": "Martinique, port unspecified",
        "Disembarkment-Latitude": 14.58390168,
        "Disembarkment-Longitude": -61.0774718,
        "Trade-Year": 1744,
        "Slave-Count": 524,
        "Captain's name": "Auffray, Toussaint",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 31648,
        "Vessel-Name": "Duchesse de Polignac",
        "Voyage-Origin": "Saint-Malo",
        "Purchase-Latitude": 48.61725746,
        "Purchase-Longitude": -2.241062493,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Port-au-Prince",
        "Disembarkment-Latitude": 18.547327,
        "Disembarkment-Longitude": -72.3395928,
        "Trade-Year": 1784,
        "Slave-Count": 638,
        "Captain's name": "Ozelle, Charles",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 33307,
        "Vessel-Name": "Pacifique",
        "Voyage-Origin": "Saint-Malo",
        "Purchase-Latitude": 48.70219548,
        "Purchase-Longitude": -1.894266883,
        "Principal-Purchase-Location": "Kormantine",
        "Voyage-Disembarkation": "Saint-Domingue, port unspecified",
        "Disembarkment-Latitude": 18.43420029,
        "Disembarkment-Longitude": -69.92960935,
        "Trade-Year": 1788,
        "Slave-Count": 516,
        "Captain's name": "Sanctos, J-Fr",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 11173,
        "Vessel-Name": "Wulpenburg",
        "Voyage-Origin": "Vlissingen",
        "Purchase-Latitude": 51.45002889,
        "Purchase-Longitude": 3.548395292,
        "Principal-Purchase-Location": "Malembo",
        "Voyage-Disembarkation": "Suriname",
        "Disembarkment-Latitude": 6.047404456,
        "Disembarkment-Longitude": -55.86611017,
        "Trade-Year": 1758,
        "Slave-Count": 511,
        "Captain's name": "Solomi, David",
        active: false,
    },
    {
        ID: uuid(),
        "Voyage-ID": 10782,
        "Vessel-Name": "Jonge Stam",
        "Voyage-Origin": "Zeeland",
        "Purchase-Latitude": 51.41373795,
        "Purchase-Longitude": 3.718548644,
        "Principal-Purchase-Location": "Cabinda",
        "Voyage-Disembarkation": "Suriname",
        "Disembarkment-Latitude": 6.047404456,
        "Disembarkment-Longitude": -55.86611017,
        "Trade-Year": 1759,
        "Slave-Count": 590,
        "Captain's name": "Hollander, Cornelis Andries",
        active: false,
    },
];
